version: '3.8'

services:
  backend:
    build: ./backend-api
    ports:
      - "5000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306   
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=qlyhocvien

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: qlyhocvien
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql

volumes:
  db_data: