version: '3.8'

services:
  backend:
    build: ./backend-api
    ports:
      - "5000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306   
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=qlyhocvien
      - DB_CHARSET=utf8mb4
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  frontend: 
    build: ./frontend
    ports:
      - "3000:80"
    environment:
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

  db:
    build: 
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: qlyhocvien
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: > 
      --default-time-zone='+07:00'
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
     

volumes:
  db_data: